version: "3"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - production
  api:
    build: .
    restart: always
    depends_on:
      - postgres
    networks:
      - production
    volumes:
      - ./config/config-production.yml:config/config-production.yml
    ports:
      - "8080:8080"
networks:
  production:
    driver: bridge