cors:
  allowOrigins: "*"
server:
  port: 8080
database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbName: postgres
  sslMode: disable
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5
redis:
  host: localhost
  port: 6379
  password: password
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 500
jwt:
  secret: "mySecretKey"